### PR TITLE
add simple pip implementation

### PR DESCRIPTION
**Pull request by simonwallin**
@iamramanjot Since I'm not a java-guy, maybe you can clean this up if needed? But anyways, this is a minimal working pip implementation that works more or less as expected.

### CODE REVIEW

**Review by shobaki — APPROVED** [review]
Tested and LGTM.

I don't know how you were able to run the app, but I had to add a `gradle.properties` to the project, containing below props:

```gradle.properties
## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Sat Dec 09 13:03:42 CET 2023
android.enableJetifier=true
android.useAndroidX=true
```
I have Gradle 7.4.

**Comment by simonwallin** [comment]
> Tested and LGTM.
> 
> I don't know how you were able to run the app, but I had to add a `gradle.properties` to the project, containing below props:
> 
> ```ini
> ## For more details on how to configure your build environment visit
> # http://www.gradle.org/docs/current/userguide/build_environment.html
> #
> # Specifies the JVM arguments used for the daemon process.
> # The setting is particularly useful for tweaking memory settings.
> # Default value: -Xmx1024m -XX:MaxPermSize=256m
> # org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
> #
> # When configured, Gradle will run in incubating parallel mode.
> # This option should only be used with decoupled projects. More details, visit
> # http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
> # org.gradle.parallel=true
> #Sat Dec 09 13:03:42 CET 2023
> android.enableJetifier=true
> android.useAndroidX=true
> ```
> 
> I have Gradle 7.4.

I had the same issue, but I chose not to commit the gradle changes, since I don't really know what is strictly needed and not.

**Comment by shobaki** [comment]
> > I have Gradle 7.4.
> 
> I had the same issue, but I chose not to commit the gradle changes, since I don't really know what is strictly needed and not.

By trial and error I came to the conclusions that only those two params were need to get it to build. I suggest we commit those separately, perhaps also while making sure credentials (if they are sensitive) are not saved in the code. Ping @iamramanjot .

**Comment by iamramanjot** [comment]
I faced the same issue with gradle. I have committed gradle folder which is required, so that it can detect it is gradle project and it has a version also which we can change.

Also done other refactoring to remove password, CU/BU which should not be there.

Otherwise looking good.

**Review by iamramanjot — APPROVED** [review]

**Pull request merged**
